<a href="https://colab.research.google.com/github/hjiwoong/DL/blob/main/day01_practice1_%ED%85%90%EC%84%9C%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch
torch.manual_seed(42) #재현성:난수 고정

print("PyTorch 버전:",torch.__version__)
print("GPU 사용 가능:", torch.cuda.is_available())

device="cuda" if torch.cuda.is_available() else "cpu" # device: 앞으로 "계산을 어디서 할지"를 담는 변수
print("사용할 장치:",device) # GPU가 있으면 "cuda", 없으면 "cpu"

PyTorch 버전: 2.11.0+cu128
GPU 사용 가능: True
사용할 장치: cuda


In [20]:
# 셀 2. 텐서 만들기 - 숫자를 담는 그릇
# 텐서(Tensor) = 숫자를 담는 다차원 배열
scalar = torch.tensor(3.0)
vector = torch.tensor([1.0,2.0,3.0])
matrix = torch.tensor([[1.0,2.0],[3.0,4.0]])

print(scalar, "| 차원:", scalar.dim(), "| 모양:", scalar.shape)
print(vector, "| 차원:", vector.dim(), "| 모양:", vector.shape)
print(matrix, "| 차원:", matrix.dim(), "| 모양:", matrix.shape)

tensor(3.) | 차원: 0 | 모양: torch.Size([])
tensor([1., 2., 3.]) | 차원: 1 | 모양: torch.Size([3])
tensor([[1., 2.],
        [3., 4.]]) | 차원: 2 | 모양: torch.Size([2, 2])


In [21]:
# 셀 3. 자주 쓰는 생성 함수
zeros = torch.zeros(2,3)
ones = torch.ones(2,3)
rand = torch.rand(2,3) # 0~1 균등분포 난수
randn = torch.randn(2,3) # 평균0, 표준편차1 정규분포 난수
arange = torch.arange(0,10,2)

print("zeros:\n", zeros)
print("ones:\n", ones)
print("rand:\n", rand)
print("randn:\n", randn)
print("arange:\n", arange)

zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
rand:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
randn:
 tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])
arange:
 tensor([0, 2, 4, 6, 8])


In [22]:
# 셀 4. 텐서 연산 - 요소별 연산과 행렬 곱
a = torch.tensor([[1.0,2.0],[3.0,4.0]])
b = torch.tensor([[10.0,20.0],[30.0,40.0]])

print("덧셈 a+b:\n", a+b)
print("곱셈 a*b:\n", a*b)

print("행렬곱 a@b:\n", a@b) # 선형대수 # 신경망의 "가중치 곱하기"는 @(행렬 곱)이다. # y=X @ W+b

print("전체 합:", a.sum())
print("평균:", a.mean())
print("최대값:", a.max(), "| 위치:", a.argmax()) #argmax는 한 줄로 편(flatten) 순서의 인덱스 번호

덧셈 a+b:
 tensor([[11., 22.],
        [33., 44.]])
곱셈 a*b:
 tensor([[ 10.,  40.],
        [ 90., 160.]])
행렬곱 a@b:
 tensor([[ 70., 100.],
        [150., 220.]])
전체 합: tensor(10.)
평균: tensor(2.5000)
최대값: tensor(4.) | 위치: tensor(3)


In [23]:
# 셀 5. 모양 바꾸기 - reshape / view
x = torch.arange(12)
print("원본:", x.shape, "| 벡터:",x)

x2 = x.reshape(3,4)
print("reshape(3,4):\n", x2) # 3행 4열로

x3 = x.reshape(2,-1) # -1 = "나머지는 알아서 계산해라"
print("reshape(2,-1) 모양:", x3.shape, "\n| 행렬:", x3)

flat = x2.flatten() # 몇 차원이든 1차원으로
print("flatten",flat.shape)

# 배치 크기는 그대로 두고 나머지를 펴라: x.reshape(batch, -1)
# x.shape: (64, 28, 28) -> (64, 784)

원본: torch.Size([12]) | 벡터: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
reshape(3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
reshape(2,-1) 모양: torch.Size([2, 6]) 
| 행렬: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
flatten torch.Size([12])


In [24]:
# 셀 6. 인덱싱과 슬라이싱 - 넘파이와 동일
m = torch.arange(20).reshape(4,5)
print("m:",m)

print("\n첫 행:", m[0])
print("첫 열:", m[:,0]) # 모든 행(:)의 0번째 열
print("부분:",m[1:3, 2:4]) # 1~2행, 2~3열
# [행,열] 순서, : 는 '전부'

m: tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

첫 행: tensor([0, 1, 2, 3, 4])
첫 열: tensor([ 0,  5, 10, 15])
부분: tensor([[ 7,  8],
        [12, 13]])


In [25]:
# 셀 7. 넘파이 ↔ 텐서 변환
import numpy as np

np_arr = np.array([1.0,2.0,3.0])
t=torch.from_numpy(np_arr) # 넘파이 → 텐서
back = t.numpy() # 텐서 → 넘파이

print("넘파이→텐서:", t, t.dtype)
print("텐서→넘파이:", back, type(back))

np_arr[0] = 100.0
print("넘파이를 바꿨더니 텐서도:", t) # from_numpy(), numpy() 넘파이는 메모리를 공유. 한 쪽을 바꾸면 다른 쪽도 바뀐다. 복사하려면 torch.tensor(np_arr)

# 넘파이의 기본 실수형은 float64, PyTorch의 기본은 float32. 섞이면 에러. dtype=torch.float32 지정
# 데이터 로딩/전처리(판다스/넘파이) → 학습(PyTorch) → 시각화(넘파이)

넘파이→텐서: tensor([1., 2., 3.], dtype=torch.float64) torch.float64
텐서→넘파이: [1. 2. 3.] <class 'numpy.ndarray'>
넘파이를 바꿨더니 텐서도: tensor([100.,   2.,   3.], dtype=torch.float64)


In [26]:
# 셀 8. GPU로 보내기 - .to(device)
x = torch.randn(3,3)
print("원래 위치:", x.device)

x_gpu = x.to(device) #GPU가 있으면 cuda로 이동
print("이동 후 위치:", x_gpu.device)

# 연산에 참여하는 텐서는 같은 장치에 있어야 한다

원래 위치: cpu
이동 후 위치: cuda:0


In [33]:
# 셀 9. 미니 퀴즈 - 손으로 예측한 뒤 실험해보기
q = torch.arange(6).reshape(2,3)

print("원본 q:",q)
print("Q1:", q.shape)

print("\nQ2:", q.sum(dim=0), q.sum(dim=0).shape) # dim=0은 0번째 차원(행)을 없애며 접는다

print("\n전치된 q.T", q.T) # 전치는 행과열 교환
print("Q3:", q@q.T, (q@q.T).shape) # @ 행렬 곱

원본 q: tensor([[0, 1, 2],
        [3, 4, 5]])
Q1: torch.Size([2, 3])

Q2: tensor([3, 5, 7]) torch.Size([3])

전치된 q.T tensor([[0, 3],
        [1, 4],
        [2, 5]])
Q3: tensor([[ 5, 14],
        [14, 50]]) torch.Size([2, 2])
